services:
  debian-wheezy:
    image: percywhite/kaigara:0.0.5-wheezy
    build:
      context: ./debian/wheezy/
      dockerfile: Dockerfile

  debian-stretch:
    image: percywhite/kaigara:0.0.5-stretch
    build:
      context: ./debian/stretch/
      dockerfile: Dockerfile

  debian-bullseye:
    image: percywhite/kaigara:0.0.5-bullseye
    build:
      context: ./debian/bullseye/
      dockerfile: Dockerfile

  debian-buster:
    image: percywhite/kaigara:0.0.5-buster
    build:
      context: ./debian/buster/
      dockerfile: Dockerfile

  alpine-3.7:
    image: percywhite/kaigara:0.0.5-alpine3.7
    build:
      context: ./alpine/3.7/
      dockerfile: Dockerfile

  alpine-3.14:
    image: percywhite/kaigara:0.0.5-alpine3.14
    build:
      context: ./alpine/3.14/
      dockerfile: Dockerfile

  ubuntu-focal:
    image: percywhite/kaigara:0.0.5-focal
    build:
      context: ./ubuntu/focal/
      dockerfile: Dockerfile